In [10]:
import numpy as np
# cau 1 a: do dai cua vector


def compute_vector_length(vector):
    # *********** Your code here ***********
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector
# cau 1b: tinh tich vo huong


def compute_dot_product(vector1, vector2):
    result = np.dot(vector1, vector2)
    return result
# cau 1c: nhan c voi ma tran


def matrix_multi_vector(matrix, vector):
    result = np.dot(matrix, vector)
    return result
# cau 1d: nhan ma tran voi ma tran


def matrix_multi_matrix(matrix1, matrix2):
    result = np.dot(matrix1, matrix2)
    return result
# cau 1e: tim ma tran nghich dao


def inverse_matrix(matrix):
    det_matrix = np.linalg.det(matrix)
    if det_matrix != 0:
        result = np.linalg.inv(matrix)
    else:
        result = None
    return result

In [2]:
#TN1
import numpy as np
vector = np.array ([-2, 4, 9, 21])
result = compute_vector_length ([ vector ])
print ( round (result ,2))

23.28


In [3]:
v1 = np. array ([0 , 1, -1, 2])
v2 = np. array ([2 , 5, 1, 0])
result = compute_dot_product (v1 , v2)
print ( round (result ,2))

4


In [4]:
#TN3
x = np. array ([[1 , 2],
[3, 4]])
k = np. array ([1 , 2])
print ('result \n', x.dot (k))

result 
 [ 5 11]


In [5]:
#TN4
x = np.array ([[ -1 , 2],
[3, -4]])
k = np.array ([1 , 2])
print ('result \n', x@k)


result 
 [ 3 -5]


In [8]:
m = np.array ([[ -1 , 1, 1], [0, -4, 9]])
v = np.array ([0 , 2, 1])
result = matrix_multi_vector (m, v)
print ( result )

[3 1]


In [11]:
m1 = np.array ([[0 , 1, 2], [2, -3, 1]])
m2 = np.array ([[1 , -3] ,[6 , 1], [0, -1]])
result = matrix_multi_matrix (m1 , m2)
print ( result )

[[  6  -1]
 [-16 -10]]


In [12]:
m1 = np.eye (3)
m2 = np.array ([[1 , 1, 1] ,[2 , 2, 2], [3, 3, 3]])
result = m1@m2
print ( result )

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [15]:
m1 = np.eye (2)
m1 = np.reshape (m1 ,( -1 ,4))[0]
m2 = np.array ([[1 , 1, 1, 1] ,[2 , 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print ( result )

[5. 5. 5. 5.]


In [16]:
#TN9
m1 = np. array ([[1 , 2], [3, 4]])
m1 = np. reshape (m1 ,( -1 ,4) , "F")[0]
m2 = np. array ([[1 , 1, 1, 1] ,[2 , 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print ( result )

[29 29 29 29]


In [17]:
#TN10
m1 = np.array ([[ -2 , 6], [8, -4]])
result = inverse_matrix (m1)
print ( result )

[[0.1  0.15]
 [0.2  0.05]]


In [18]:
import numpy as np
def compute_eigenvalues_eigenvectors ( matrix ):
# Tính eigenvalues và eigenvectors   
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues , eigenvectors

In [19]:
#TN11
matrix = np.array ([[0.9 , 0.2] , [0.1 , 0.8]])
eigenvalues , eigenvectors = compute_eigenvalues_eigenvectors ( matrix )
print ( eigenvectors )

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [20]:
def compute_cosine (v1 , v2):
    cos_sim=np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))
    return cos_sim

In [21]:
#TN12
x = np.array ([1 , 2, 3, 4])
y = np.array ([1 , 0, 3, 0])
result = compute_cosine (x,y)
print ( round (result , 3))

0.577
