In [1]:
import numpy as np

In [ ]:
class CustomLinearRegression :
    def __init__ (self , X_data , y_target , learning_rate =0.01 , num_epochs =10000) :
        self.num_samples = X_data.shape [0]
        self.X_data = np.c_[np. ones (( self.num_samples , 1)), X_data ]
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs

        # Initial weights
        self.theta = np. random.randn ( self.X_data.shape [1] , 1)
        self.losses = []

    def compute_loss (self , y_pred , y_target ):       
        # compute loss
        
        return loss
    def predict (self , X_data ):
        y_pred = X_data.dot ( theta )
        return y_pred
    def fit( self ):
        for epoch in range ( self.num_epochs ):

            #*** Your Code Here ***
            y_pred=self.predict(self.X_data)
            loss = self.compute_loss (y_pred , self.y_target )
            self.losses.append ( loss )
            # compute gradient
            loss_grd = 2*( y_pred - self.y_target )/ self.num_samples
            gradients = self.X_data .T.dot( loss_grd )
            # update weight
            self.theta = self.theta - self.learning_rate * gradients
            if ( epoch % 50) == 0:
                print (f'Epoch : { epoch } - Loss : { loss }')

        return {
            'loss': sum( self.losses )/len( self.losses ),
            'weight': self.theta
        }
        
 

In [2]:
def r2score (y_pred , y):
    rss = np.sum (( y_pred - y) ** 2)
    tss = np.sum ((y-y. mean ()) ** 2)
    r2 = 1 - (rss / tss)
    return r2

In [6]:
# Case 1
y_pred = np. array ([1 , 2, 3, 4, 5])
y = np. array ([1 , 2, 3, 4, 5])
t=r2score (y_pred , y)
print(t)

1.0


In [7]:
# Case 2
y_pred = np. array ([1 , 2, 3, 4, 5])
y = np. array ([3 , 5, 5, 2, 4])
t=r2score (y_pred , y)
print(t)

-2.235294117647059


In [3]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [1]:
def create_polynomial_features (X, degree =2):
    """ Creates the polynomial features
    Args :
    X: A array tensor for the data .
    degree : A intege for the degree of
    the generated polynomial function .
    """
    X_new = X
    for d in range(2, degree + 1):
        X_new = np.c_[X_new, np.power(X, d)]    
    return X_new


In [4]:

X = np.array ([[1] , [2] , [3]])

In [7]:
X_new=create_polynomial_features(X,3)

In [8]:
X_new

array([[ 1,  1,  1],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [26]:
def create_polynomial_features (X, degree =2):
    """ Creates the polynomial features
    Args :
    X: A array for the data .
    degree : A intege for the degree of
    the generated polynomial function .
    """
    X_mem = []
    for X_sub in X.T:
       # X_sub = X_sub .T
        X_new = X_sub
        print(X_new)
        for d in range (2, degree +1):
            X_new = np.c_[X_new , np. power (X_sub , d)]
        X_mem . extend ( X_new .T)
    return np.c_[ X_mem ].T

In [27]:
X = np. array ([[1 , 2],
[2, 3],
[3, 4]])
degree = 2
X_new=create_polynomial_features(X,degree)


[1 2 3]
[2 3 4]


In [28]:
X_new

array([[ 1,  1,  2,  4],
       [ 2,  4,  3,  9],
       [ 3,  9,  4, 16]])

# Sales predection

In [43]:
import numpy as np


In [44]:
import pandas as pd

In [35]:
df=pd.read_csv('SalesPrediction.csv')

In [45]:
df.describe()

TV        Radio  Social Media        Sales
count  4572.000000  4572.000000   4572.000000  4572.000000
mean     54.066857    18.160356      3.323956   192.466602
std      26.096461     9.672723      2.211218    93.071947
min      10.000000     0.000684      0.000031    31.199409
25%      32.000000    10.546519      1.529879   112.397660
50%      53.000000    17.875181      3.057150   189.632530
75%      77.000000    25.647476      4.805832   272.414914
max     100.000000    48.871161     13.981662   364.079751

In [46]:
df = pd. get_dummies (df)

In [47]:
print(df)

        TV      Radio  Social Media       Sales  Influencer_Macro  \
0     16.0   6.566231      2.907983   54.732757             False   
1     13.0   9.237765      2.409567   46.677897             False   
2     41.0  15.886446      2.913410  150.177829             False   
3     83.0  30.020028      6.922304  298.246340             False   
4     15.0   8.437408      1.405998   56.594181             False   
...    ...        ...           ...         ...               ...   
4567  26.0   4.472360      0.717090   94.685866             False   
4568  71.0  20.610685      6.545573  249.101915             False   
4569  44.0  19.800072      5.096192  163.631457             False   
4570  71.0  17.534640      1.940873  253.610411              True   
4571  42.0  15.966688      5.046548  148.202414             False   

      Influencer_Mega  Influencer_Micro  Influencer_Nano  
0                True             False            False  
1                True             False            Fa

In [49]:
df = df. fillna (df. mean ())
# Get features
X = df [['TV', 'Radio', 'Social Media', 'Influencer_Macro', 'Influencer_Mega', 'Influencer_Micro', 'Influencer_Nano']]
y = df [['Sales']]
# Train Test Split
from sklearn . model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split (
X,
y,
test_size =0.33 ,
random_state =0
)

In [50]:
from sklearn . preprocessing import StandardScaler
scaler = StandardScaler ()
X_train_processed = scaler . fit_transform ( X_train )
scaler . mean_ [0]

54.173577723283785

In [56]:
X_test_processed = scaler . fit_transform ( X_test )

In [58]:
from sklearn . preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures ( degree =2)
X_train_poly = poly_features . fit_transform ( X_train_processed )
X_test_poly = poly_features . fit_transform ( X_test_processed )

In [59]:
from sklearn . linear_model import LinearRegression
from sklearn . metrics import r2_score
poly_model = LinearRegression ()
poly_model .fit( X_train_poly , y_train )
preds = poly_model . predict ( X_test_poly )
r2_score (y_test , preds )

-8.87604557350198e+20