In [1]:
#cau 1
import numpy as np
arr = np.arange(0,10,1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
#cau 2
import numpy as np
arr = np.ones ((3 ,3) ) > 0
print(arr)
arr = np.ones ((3 ,3) , dtype = bool )
print(arr)
arr = np.full((3,3),fill_value = True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
# cau 3
import numpy as np 
arr = np.arange(0,10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


In [4]:
# cau 4
import numpy as np 
arr = np.arange(0,10)
arr[arr%2==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [5]:
#cau 5
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2,-1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
# cau 6
import numpy as np
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([arr1,arr2], axis=0)
print("Result: \n",c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
# cau 7
import numpy as np 
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([arr1,arr2], axis=1)
print("C =",c)

C = [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [8]:
# cau 8
import numpy as np
arr = np.array([1,2,3])
print(np.repeat(arr,3))
print(np.tile(arr,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [9]:
# cau 9 
import numpy as np
a = np.array([2,6,1,9,10,3,27])
index = np.where((a>=5)&(a<=10))
print('Result = ', a[index])

Result =  [ 6  9 10]


In [10]:
# cau 10
import numpy as np

def maxx(x,y):
    if x >= y:
        return x
    else:
        return y
    
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

pair_max = np.vectorize(maxx,otypes=[float])
print(pair_max(a,b))

[6. 7. 9. 8. 9. 7. 5.]


In [11]:
# cau 11
import numpy as np 
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

print("Result",np.where(a<b,b,a))

Result [6 7 9 8 9 7 5]
